use_frameworks!

platform :ios, '10.0'

target 'TestResponseChain_Example' do
  pod 'TestResponseChain', :path => '../'
  pod 'R.swift', '~> 6.1.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'RxDataSources', '~> 5.0.0'
  pod "RxGesture", '~> 4.0.4'
  pod 'RxSwiftExt', '~> 6.0.1'
  pod 'NSObject+Rx', '~> 5.2.2'
  pod 'SnapKit', '~> 5.6.0'
  pod 'LookinServer', '1.0.6', :configurations => ['Debug']
  target 'TestResponseChain_Tests' do
    inherit! :search_paths

    
  end
end
