use_frameworks!

platform :ios, '10.0'

target 'TestResponseChain_Example' do
  pod 'TestResponseChain', :path => '../'

  target 'TestResponseChain_Tests' do
    inherit! :search_paths

    
  end
end
